language: cpp
dist: bionic
os:
  - linux
compiler:
  - gcc
  - clang

# Install all of the dependencies:
install:
  - sudo apt-get -qq update
  - sudo apt-get -qq upgrade
  - sudo apt-get install -y libfltk1.3-dev cmake libglu1-mesa-dev freeglut3-dev mesa-common-dev libpng-dev libjpeg-dev
  - sudo apt-get -qq autoremove

# Execute all of the commands which should make the build pass or fail
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_PLAYER_PLUGIN=OFF -DCMAKE_INSTALL_PREFIX=$(pwd)/install ..
  - make
  - make install
